### ISSUE TITLE
Document that it is allowed to have both author and maintainer as false

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/example#24]
We now permit both of these to be false for contributors who are neither authors nor maintainers. This is useful to give credits to contributors who are in neither of the two categories. The comment should be updated to explain that.

https://github.com/gap-packages/example/blob/e9593b07adaed84c39ca762ca1eacbcedc20a168/PackageInfo.g#L152-L155

This shows that again we managed to change `ValidatePackageInfo` without updating the sample `PackageInfo.g` file :(

**Comment by fingolfin** [comment]
Yeah, that those two can get out of sync to me once again shows that having the documentations for something in a separate repository than that something is a bad idea...

**Comment by alex-konovalov** [comment]
Solution? Detailed documentation for PackageInfo.g format in Section https://www.gap-system.org/Manuals/doc/ref/chap76.html#X7A09C63685065B01 and adding all its entries into index?
